name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Maven test
    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Run the Maven verify phase
      run: mvn test
